### ISSUE TITLE
关于如果没有登陆，每次进去app都有首屏的介绍页

### ISSUE THREAD

**Issue by jiandaima** [burgessjp/GanHuoIO#1]
1.关于如果没有登陆，每次进去app都有首屏的介绍页。不知道，这是否是有意强调登陆的作用吗，还是设计上的bug，
2.最新页面的顶部，有个短短的黑线。。这个是？？

**Comment by burgessjp** [comment]
这个确实是我的问题，下个版本更新。那条短线是page的指示器，可以左右滑动的。
