### ISSUE TITLE
这是具体的报错

### ISSUE THREAD

**Issue by dongdongge** [burgessjp/GanHuoIO#19]
![s 7 vv8 s zxhw0y ycdq](https://cloud.githubusercontent.com/assets/17643741/24535613/b7f987de-1607-11e7-9cc5-9d5019d21d3f.png)
![s 7 vv8 s zxhw0y ycdq](https://cloud.githubusercontent.com/assets/17643741/24535631/d16c8130-1607-11e7-88ce-570fe36cd558.png)

**Comment by burgessjp** [comment]
删掉即可

**Comment by dongdongge** [comment]
Ok
