### ISSUE TITLE
注册Bomb失败，导致应用闪退

### ISSUE THREAD

**Issue by liucxu** [burgessjp/GanHuoIO#7]
1、SinaWeiBoShare编译不过，原因是java文件名字与类名不一致导致的
2、改过之后可以编译通过，但是在GanHuoIOApplication中的Bmob.initialize(this, "caed915330178bff62bfd281b627c77f");出现调用native代码失败
希望楼主能修改一下，我实在想学习下，谢谢。

**Comment by burgessjp** [comment]
第一个确实是这个原因。
但是第二个，我这里没问题，你能贴一下错误详细信息吗
（最近有点忙，很抱歉现在才回复）

**Comment by liucxu** [comment]
[GanhuoIOLog.txt](https://github.com/burgessjp/GanHuoIO/files/453224/GanhuoIOLog.txt)
上面是我这边抓的Log，按照Log指向的是Application类GanHuoIOApplication中注册Bomb的时候，你看下
你本地代码如果没有问题可否重新clone一个与Github上完全一致的代码看看能否正常运行呢，谢谢啊。

**Comment by burgessjp** [comment]
我check下来任然没问题，你是不是在模拟器中运行的？

**Comment by liucxu** [comment]
不是模拟器 xiaomiNote 原生6.0.0系统 
我这边只要把注册bomb这行注释掉就不会报错，就可以正常编译运行了。

**Comment by burgessjp** [comment]
这我就不太清楚了
